### ISSUE TITLE
Can't build MPI.jl on Travis-CI

### ISSUE THREAD

**Issue by dpo** [JuliaParallel/MPI.jl#213]
I'm starting to feel a bit helpless, totally unable to build MPI.jl on Linux or MacOS on Travis-CI. My package MUMPS.jl depends on MPI.jl.

I used to `apt-get install libopenmpi-dev openmpi-bin` on Linux, but that broke recently with compilation errors when building MPI.jl (certain symbols not having an implicit type). Inspired by MPI.jl's own `.travis.yml`, I decided to try building OpenMPI 3.0.0 from source, but [that fails too](https://travis-ci.org/JuliaSmoothOptimizers/MUMPS.jl/jobs/418013300#L3902).

On MacOS, I `brew install open-mpi`, and that still works with Julia 0.6, but [not with Julia 0.7](https://travis-ci.org/JuliaSmoothOptimizers/MUMPS.jl/jobs/418013304#L972).

Any help would be greatly appreciated!

Thank you.

**Comment by barche** [comment]
Regarding the first error, I would suggest setting the `CC` and `FC` environment variables to the MPI compilers, as done here: https://github.com/JuliaParallel/MPI.jl/blob/master/.travis.yml#L18-L19

The error with the `VERSION` file should be fixed on MPI.jl v0.7.0, but you seem to be getting v0.6.0.

**Comment by barche** [comment]
I think that `CC` and `FC` only need to be set if MPI is in a non-standard location, otherwise CMake is able to find it on its own. But usually MPI packages recommend using the compiler wrappers, so it's a good idea to always do this.

I don't really think it's worth the trouble to support both Julia 0.6 and 0.7 using the same version of your package, I'd just make a final Julia-0.6 compatible release and then bump the version for the Julia 0.7-compatible release that no longer supports Julia 0.6.

**Comment by einzigsue** [comment]
Does MPI.jl working with julia v1.0.0 now?

**Comment by barche** [comment]
Yes, it should work, I'm not sure if you need the latest master or not though.

**Comment by einzigsue** [comment]
I think it must be something changed in v1.0.0 about the type cmd. The original build.jl give me the error 

┌ Error: Error building `MPI`: 
│ Unreachable reached at 0x7f966e456c29
│ 
│ signal (4): Illegal instruction

I fixed the build by hard-coding the fortran library path into the variable configure directly instead of using the loop to add all the -D flags in.

**Comment by dpo** [comment]
Still no luck for me unfortunately: https://travis-ci.org/JuliaSmoothOptimizers/MUMPS.jl/jobs/432536120#L1020

Any suggestions?

**Comment by dpo** [comment]
On Travis-CI, Julia 0.7, 1.0 and nightly all say
```
ERROR: The following package names could not be resolved:
 * MPI (da04e1cc-30fd-572f-bb4f-1f8673147195 in manifest but not in project)
Please specify by known `name=uuid`.
```
Is any Julia project able to depend on MPI.jl???

**Comment by vchuravy** [comment]
@dpo See https://github.com/JuliaSmoothOptimizers/MUMPS.jl/pull/30/files#r220339227
That looks like an unrelated problem

**Comment by lcw** [comment]
I have a julia project that I am working on that uses MPI.jl.  It is still rough so not documented but  see [Canary.jl](https://github.com/climate-machine/Canary.jl) and its travis file [`.travis.yml`](https://github.com/climate-machine/Canary.jl/blob/c636b806282c58f1111c81fa3ce3da1c8cb25bef/.travis.yml).

**Comment by vchuravy** [comment]
Please try with https://github.com/JuliaParallel/MPI.jl/releases/tag/v0.7.1

**Comment by dpo** [comment]
Thanks. I don't see any difference, unfortunately. But now it looks like the issue is with BinDeps.

**Comment by dpo** [comment]
Thanks for the help here. Finally I can build, so I can close this issue.
